"use client";

import React, { useState, useCallback } from 'react';
import { Bot, Code, Play, Terminal, LayoutTemplate, GitBranch, Share2, Send, Bell, Settings } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { AgentStatus, type Agent } from '@/components/agentic-studio/agent-status';
import { FileTree, type FileNode } from '@/components/agentic-studio/file-tree';
import { ChatView, type Message } from '@/components/agentic-studio/chat-view';
import { CodeEditorView } from '@/components/agentic-studio/code-editor';
import { CanvasView } from '@/components/agentic-studio/canvas-view';
import { LivePreview } from '@/components/agentic-studio/live-preview';
import { LogsView, type Log } from '@/components/agentic-studio/logs-view';
import { useToast } from "@/hooks/use-toast"

// Mock Data
const initialFileStructure: FileNode = {
  name: 'recipe-app',
  type: 'folder',
  children: [
    {
      name: 'src',
      type: 'folder',
      children: [
        {
          name: 'components',
          type: 'folder',
          children: [
            { name: 'Button.jsx', type: 'file' },
            { name: 'RecipeCard.jsx', type: 'file' },
          ],
        },
        {
          name: 'pages',
          type: 'folder',
          children: [
            { name: 'HomePage.jsx', type: 'file' },
            { name: 'LoginPage.jsx', type: 'file', status: 'generating' },
          ],
        },
        { name: 'App.jsx', type: 'file' },
        { name: 'index.css', type: 'file' },
      ],
    },
    { name: 'package.json', type: 'file' },
    { name: 'README.md', type: 'file' },
  ],
};

const initialAgents: Agent[] = [
  { id: 1, name: 'Requirements Analyst', status: 'Idle', progress: 0 },
  { id: 2, name: 'UI/UX Architect', status: 'Idle', progress: 0 },
  { id: 3, name: 'Frontend Coder', status: 'Idle', progress: 0 },
  { id: 4, name: 'Backend Coder', status: 'Idle', progress: 0 },
  { id: 5, name: 'QA & Security Agent', status: 'Idle', progress: 0 },
  { id: 6, name: 'DevOps & Deployment', status: 'Idle', progress: 0 },
];

const codeContent: { [key: string]: string } = {
  'LoginPage.jsx': `
import React, { useState } from 'react';

// Generated by Frontend Coder Agent
// Task: Create a login form

export default function LoginPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();
    // TODO: Implement Supabase Auth call
    console.log('Logging in with:', { email, password });
  };

  return (
    <div className="flex items-center justify-center h-screen bg-gray-100">
      <div className="w-full max-w-md p-8 space-y-6 bg-white rounded-lg shadow-md">
        <h2 className="text-2xl font-bold text-center">Login</h2>
        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label htmlFor="email" className="text-sm font-medium">Email</label>
            <input
              id="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full px-3 py-2 mt-1 border border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 text-gray-900"
              required
            />
          </div>
          <div>
            <label htmlFor="password" className="text-sm font-medium">Password</label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full px-3 py-2 mt-1 border border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 text-gray-900"
              required
            />
          </div>
          <button type="submit" className="w-full py-2 text-white bg-indigo-600 rounded-md hover:bg-indigo-700">
            Log In
          </button>
        </form>
      </div>
    </div>
  );
}
  `,
};

export default function AgenticStudioPage() {
  const [fileStructure, setFileStructure] = useState<FileNode>(initialFileStructure);
  const [agents, setAgents] = useState<Agent[]>(initialAgents);
  const [centerView, setCenterView] = useState('chat');
  const [rightView, setRightView] = useState('preview');
  const [messages, setMessages] = useState<Message[]>([
    { sender: 'ai', text: 'Welcome to **Agentic Studio**! I am your AI project manager and orchestrator. Tell me what you would like to build.' }
  ]);
  const [logs, setLogs] = useState<Log[]>([]);
  const [activeCodeFile, setActiveCodeFile] = useState('LoginPage.jsx');
  const { toast } = useToast();

  const addLog = useCallback((agent: string, message: string, color: string = 'text-green-400') => {
      const timestamp = new Date().toLocaleTimeString('en-US', { hour12: false });
      setLogs(prev => [...prev, { timestamp, agent, message, color }]);
  }, []);

  const runAgentWorkflow = useCallback(() => {
    let currentAgents = [...initialAgents];
    
    const updateAgent = (id: number, status: Agent['status'], progress: number) => {
        currentAgents = currentAgents.map(a => a.id === id ? { ...a, status, progress } : a);
        setAgents([...currentAgents]);
    };

    addLog('Orchestrator', 'Received request to create a login page.', 'text-yellow-300');
    
    setTimeout(() => {
        addLog('Orchestrator', 'Analyzing requirements...');
        updateAgent(1, 'Working', 50);
    }, 500);

    setTimeout(() => {
        updateAgent(1, 'Working', 100);
        addLog('Requirements Analyst', 'Specifications extracted. Input: text, Output: PRD.', 'text-cyan-400');
    }, 1500);

    setTimeout(() => {
        updateAgent(1, 'Done', 100);
        addLog('Orchestrator', 'Assigning task to UI/UX Architect.');
        updateAgent(2, 'Working', 25);
    }, 2000);

    setTimeout(() => {
        addLog('UI/UX Architect', 'Generating wireframe in Gemini Canvas...', 'text-purple-400');
        updateAgent(2, 'Working', 75);
        setCenterView('canvas');
        toast({ title: "UI/UX Agent", description: "Gemini Canvas has been updated."});
    }, 3000);

    setTimeout(() => {
        updateAgent(2, 'Done', 100);
        addLog('Orchestrator', 'Design approved. Assigning task to Frontend Coder.');
        updateAgent(3, 'Working', 10);
    }, 4500);
    
    setTimeout(() => {
        addLog('Frontend Coder', 'Creating file `src/pages/LoginPage.jsx`...', 'text-pink-400');
        updateAgent(3, 'Working', 30);
        setFileStructure(prev => {
            const newStruct = JSON.parse(JSON.stringify(prev));
            newStruct.children[0].children[1].children[1].status = 'generating';
            return newStruct;
        });
    }, 5500);

    setTimeout(() => {
        addLog('Frontend Coder', 'Writing React code for the login form.', 'text-pink-400');
        updateAgent(3, 'Working', 80);
        setCenterView('code');
        setActiveCodeFile('LoginPage.jsx');
        toast({ title: "Frontend Agent", description: "Code for LoginPage.jsx has been generated."});
    }, 7000);

    setTimeout(() => {
        updateAgent(3, 'Done', 100);
        addLog('Frontend Coder', 'Component `LoginPage` is ready for review.', 'text-pink-400');
        setFileStructure(prev => {
            const newStruct = JSON.parse(JSON.stringify(prev));
            newStruct.children[0].children[1].children[1].status = 'done';
            return newStruct;
        });
        setMessages(prev => [...prev, { sender: 'ai', text: 'The Frontend Coder has finished implementing `LoginPage.jsx`. The code is ready for review in the **Code** tab and a preview is available in the **Live Preview**.' }]);
    }, 9000);
    
    setTimeout(() => {
        addLog('Orchestrator', 'Assigning task to QA Agent.');
        updateAgent(5, 'Working', 20);
    }, 9500);

    setTimeout(() => {
        addLog('QA & Security', 'Running unit tests for `LoginPage.jsx`...', 'text-teal-400');
        updateAgent(5, 'Working', 70);
    }, 10500);

    setTimeout(() => {
        updateAgent(5, 'Done', 100);
        addLog('QA & Security', 'Tests passed. Coverage: 85%. No critical vulnerabilities found.', 'text-teal-400');
        setMessages(prev => [...prev, { sender: 'ai', text: 'The QA Agent has confirmed the code quality and security. Awaiting your approval or further instructions.' }]);
    }, 12000);

  }, [addLog, toast]);

  const handleSendMessage = useCallback((text: string) => {
    setMessages(prev => [...prev, { sender: 'user', text }]);
    
    if (text.toLowerCase().includes('login page')) {
        setTimeout(() => {
            setMessages(prev => [...prev, { sender: 'ai', text: 'Understood. Starting the workflow to create a login page. I will keep you updated on the progress.' }]);
            runAgentWorkflow();
        }, 1000);
    } else {
        setTimeout(() => {
            setMessages(prev => [...prev, { sender: 'ai', text: 'Your instruction has been noted. I am currently configured for a demo workflow for a "login page". Try giving that instruction.' }]);
        }, 1000);
    }
  }, [runAgentWorkflow]);

  return (
    <div className="bg-[#111827] text-white h-screen flex flex-col font-sans">
      <header className="flex items-center justify-between h-14 px-4 border-b border-gray-700 flex-shrink-0">
        <div className="flex items-center space-x-4">
          <Bot size={24} className="text-blue-400" />
          <h1 className="text-lg font-grotesk font-bold">Agentic Studio</h1>
          <div className="flex items-center bg-gray-700/50 px-3 py-1 rounded-md text-sm">
            <GitBranch size={14} className="mr-2" />
            <span>main</span>
          </div>
        </div>
        <div className="flex items-center space-x-4">
          <Button variant="default" size="sm" className="bg-primary hover:bg-primary/90">
            <Share2 size={14} className="mr-2" />
            Share
          </Button>
          <Button variant="ghost" size="icon" className="text-gray-400 hover:text-white">
            <Bell size={20} />
          </Button>
          <Button variant="ghost" size="icon" className="text-gray-400 hover:text-white">
            <Settings size={20} />
          </Button>
          <Avatar>
            <AvatarFallback className="bg-indigo-500 text-white font-bold text-sm">P</AvatarFallback>
          </Avatar>
        </div>
      </header>

      <div className="flex flex-1 overflow-hidden">
        <div className="w-1/5 min-w-[280px] bg-gray-800/50 border-r border-gray-700 flex flex-col">
          <div className="p-4 border-b border-gray-700">
            <h2 className="text-md font-grotesk font-semibold">Explorer</h2>
          </div>
          <div className="flex-1 overflow-y-auto py-2">
            <FileTree node={fileStructure} />
          </div>
          <div className="border-t border-gray-700 flex-shrink-0">
            <AgentStatus agents={agents} />
          </div>
        </div>

        <div className="w-2/5 flex flex-col border-r border-gray-700">
          <div className="flex-shrink-0 border-b border-gray-700">
            <div className="flex space-x-1 p-2">
              <button onClick={() => setCenterView('chat')} className={`flex items-center px-4 py-2 text-sm rounded-md ${centerView === 'chat' ? 'bg-gray-700' : 'hover:bg-gray-700/50 text-gray-300'}`}>
                <Bot size={16} className="mr-2" /> Chat
              </button>
              <button onClick={() => setCenterView('code')} className={`flex items-center px-4 py-2 text-sm rounded-md ${centerView === 'code' ? 'bg-gray-700' : 'hover:bg-gray-700/50 text-gray-300'}`}>
                <Code size={16} className="mr-2" /> Code
              </button>
              <button onClick={() => setCenterView('canvas')} className={`flex items-center px-4 py-2 text-sm rounded-md ${centerView === 'canvas' ? 'bg-gray-700' : 'hover:bg-gray-700/50 text-gray-300'}`}>
                <LayoutTemplate size={16} className="mr-2" /> Canvas
              </button>
            </div>
          </div>
          <div className="flex-1 overflow-hidden bg-gray-800/50">
            {centerView === 'chat' && <ChatView messages={messages} onSendMessage={handleSendMessage} />}
            {centerView === 'code' && <CodeEditorView content={codeContent[activeCodeFile] || 'Select a file to view its code.'} />}
            {centerView === 'canvas' && <CanvasView />}
          </div>
        </div>

        <div className="w-2/5 flex flex-col bg-gray-800/30">
          <div className="flex-shrink-0 border-b border-gray-700">
            <div className="flex space-x-1 p-2">
              <button onClick={() => setRightView('preview')} className={`flex items-center px-4 py-2 text-sm rounded-md ${rightView === 'preview' ? 'bg-gray-700' : 'hover:bg-gray-700/50 text-gray-300'}`}>
                <Play size={16} className="mr-2" /> Live Preview
              </button>
              <button onClick={() => setRightView('logs')} className={`flex items-center px-4 py-2 text-sm rounded-md ${rightView === 'logs' ? 'bg-gray-700' : 'hover:bg-gray-700/50 text-gray-300'}`}>
                <Terminal size={16} className="mr-2" /> Logs
              </button>
            </div>
          </div>
          <div className="flex-1 overflow-hidden p-4">
            {rightView === 'preview' && <LivePreview />}
            {rightView === 'logs' && <LogsView logs={logs} />}
          </div>
        </div>
      </div>
    </div>
  );
}
