
"use client";

import React, { useState } from 'react';
import { Bot, Code, Play, Terminal, LayoutTemplate, GitBranch, Share2, Upload, Download, ArrowUp, Send, Bell, Settings } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { AgentStatus, type Agent } from '@/components/agentic-studio/agent-status';
import { FileTree, type FileNode } from '@/components/agentic-studio/file-tree';
import { ChatView, type Message } from '@/components/agentic-studio/chat-view';
import { CodeEditorView } from '@/components/agentic-studio/code-editor';
import { CanvasView } from '@/components/agentic-studio/canvas-view';
import { LivePreview } from '@/components/agentic-studio/live-preview';
import { LogsView, type Log } from '@/components/agentic-studio/logs-view';
import { useToast } from "@/hooks/use-toast"

// Mock Data
const initialFileStructure: FileNode = {
  name: 'recipe-app',
  type: 'folder',
  children: [
    {
      name: 'src',
      type: 'folder',
      children: [
        {
          name: 'components',
          type: 'folder',
          children: [
            { name: 'Button.jsx', type: 'file' },
            { name: 'RecipeCard.jsx', type: 'file' },
          ],
        },
        {
          name: 'pages',
          type: 'folder',
          children: [
            { name: 'HomePage.jsx', type: 'file' },
            { name: 'LoginPage.jsx', type: 'file', status: 'generating' },
          ],
        },
        { name: 'App.jsx', type: 'file' },
        { name: 'index.css', type: 'file' },
      ],
    },
    { name: 'package.json', type: 'file' },
    { name: 'README.md', type: 'file' },
  ],
};

const initialAgents: Agent[] = [
  { id: 1, name: 'Requirements Analyst', status: 'Idle', progress: 0 },
  { id: 2, name: 'UI/UX Architect', status: 'Idle', progress: 0 },
  { id: 3, name: 'Frontend Coder', status: 'Idle', progress: 0 },
  { id: 4, name: 'Backend Coder', status: 'Idle', progress: 0 },
  { id: 5, name: 'QA & Security Agent', status: 'Idle', progress: 0 },
  { id: 6, name: 'DevOps & Deployment', status: 'Idle', progress: 0 },
];

const codeContent: { [key: string]: string } = {
  'LoginPage.jsx': `
import React, { useState } from 'react';

// Generated by Frontend Coder Agent
// Task: Create a login form

export default function LoginPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();
    // TODO: Implement Supabase Auth call
    console.log('Logging in with:', { email, password });
  };

  return (
    <div className="flex items-center justify-center h-screen bg-gray-100">
      <div className="w-full max-w-md p-8 space-y-6 bg-white rounded-lg shadow-md">
        <h2 className="text-2xl font-bold text-center">Login</h2>
        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label htmlFor="email" className="text-sm font-medium">Email</label>
            <input
              id="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full px-3 py-2 mt-1 border border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 text-gray-900"
              required
            />
          </div>
          <div>
            <label htmlFor="password" className="text-sm font-medium">Password</label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full px-3 py-2 mt-1 border border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 text-gray-900"
              required
            />
          </div>
          <button type="submit" className="w-full py-2 text-white bg-indigo-600 rounded-md hover:bg-indigo-700">
            Log In
          </button>
        </form>
      </div>
    </div>
  );
}
  `,
};

export default function AgenticStudioPage() {
  const [fileStructure, setFileStructure] = useState<FileNode>(initialFileStructure);
  const [agents, setAgents] = useState<Agent[]>(initialAgents);
  const [centerView, setCenterView] = useState('chat');
  const [rightView, setRightView] = useState('preview');
  const [messages, setMessages] = useState<Message[]>([
    { sender: 'ai', text: 'Welcome to **Agentic Studio**! I am your AI project manager and orchestrator. Tell me what you would like to build.' }
  ]);
  const [logs, setLogs] = useState<Log[]>([]);
  const [activeCodeFile, setActiveCodeFile] = useState('LoginPage.jsx');
  const { toast } = useToast();

  const handleSendMessage = (text: string) => {
    setMessages(prev => [...prev, { sender: 'user', text }]);
    // Mock AI response
    setTimeout(() => {
        setMessages(prev => [...prev, { sender: 'ai', text: 'Your instruction has been noted. I will begin working on it shortly.' }]);
    }, 1000);
  };

  return (
    <div className="bg-background text-foreground h-screen flex flex-col font-sans">
      <header className="flex items-center justify-between h-14 px-4 border-b border-border flex-shrink-0 bg-card">
        <div className="flex items-center space-x-4">
          <Bot size={24} className="text-primary" />
          <h1 className="text-lg font-grotesk font-bold">Synapse IDE</h1>
          <div className="flex items-center bg-muted px-3 py-1 rounded-md text-sm">
            <GitBranch size={14} className="mr-2" />
            <span>main</span>
          </div>
          <Button variant="outline" size="sm" onClick={() => toast({ title: "Committing...", description: "Staging changes and committing to the local branch." })}>
            Commit
          </Button>
          <div className="flex items-center space-x-1">
            <Button variant="outline" size="sm" onClick={() => toast({ title: "Pushing...", description: "Pushing changes to the remote repository." })}>
              <ArrowUp size={14} className="mr-2" />
              Push
            </Button>
            <Button variant="outline" size="sm" onClick={() => toast({ title: "Pulling...", description: "Fetching and merging changes from the remote." })}>
              <Download size={14} className="mr-2" />
              Pull
            </Button>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <Button variant="default" size="sm" onClick={() => toast({ title: "Shared", description: "Project shared successfully." })}>
            <Share2 size={14} className="mr-2" />
            Share
          </Button>
          <Button variant="ghost" size="icon" className="text-muted-foreground hover:text-foreground" onClick={() => toast({ title: "Notifications", description: "No new notifications." })}>
            <Bell size={20} />
          </Button>
          <Button variant="ghost" size="icon" className="text-muted-foreground hover:text-foreground" onClick={() => toast({ title: "Settings", description: "Settings page is not implemented yet." })}>
            <Settings size={20} />
          </Button>
          <Avatar>
            <AvatarFallback className="bg-primary text-primary-foreground font-bold text-sm">U</AvatarFallback>
          </Avatar>
        </div>
      </header>

      <main className="flex flex-1 overflow-hidden">
        {/* Left Panel: Navigation & Agent Overview */}
        <div className="w-1/5 min-w-[280px] bg-card border-r border-border flex flex-col">
          <div className="p-4 border-b border-border">
            <h2 className="text-md font-grotesk font-semibold">Explorer</h2>
          </div>
          <div className="flex-1 overflow-y-auto py-2">
            <FileTree node={fileStructure} />
          </div>
          <div className="border-t border-border flex-shrink-0">
            <AgentStatus agents={agents} />
          </div>
        </div>

        {/* Center Panel: Dynamic Workspace */}
        <div className="w-2/5 flex flex-col border-r border-border">
          <div className="flex-shrink-0 border-b border-border bg-card">
            <div className="flex space-x-1 p-2">
              <Button variant={centerView === 'chat' ? 'secondary' : 'ghost'} size="sm" onClick={() => setCenterView('chat')}>
                <Bot size={16} className="mr-2" /> Chat
              </Button>
              <Button variant={centerView === 'code' ? 'secondary' : 'ghost'} size="sm" onClick={() => setCenterView('code')}>
                <Code size={16} className="mr-2" /> Code
              </Button>
              <Button variant={centerView === 'canvas' ? 'secondary' : 'ghost'} size="sm" onClick={() => setCenterView('canvas')}>
                <LayoutTemplate size={16} className="mr-2" /> Canvas
              </Button>
            </div>
          </div>
          <div className="flex-1 overflow-hidden bg-background">
            {centerView === 'chat' && <ChatView messages={messages} onSendMessage={handleSendMessage} />}
            {centerView === 'code' && <CodeEditorView content={codeContent[activeCodeFile] || 'Select a file to view its code.'} />}
            {centerView === 'canvas' && <CanvasView />}
          </div>
        </div>

        {/* Right Panel: Immediate Feedback */}
        <div className="w-2/5 flex flex-col bg-muted/30">
          <div className="flex-shrink-0 border-b border-border bg-card">
            <div className="flex space-x-1 p-2">
              <Button variant={rightView === 'preview' ? 'secondary' : 'ghost'} size="sm" onClick={() => setRightView('preview')}>
                 <Play size={16} className="mr-2" /> Live Preview
              </Button>
              <Button variant={rightView === 'logs' ? 'secondary' : 'ghost'} size="sm" onClick={() => setRightView('logs')}>
                <Terminal size={16} className="mr-2" /> Logs
              </Button>
            </div>
          </div>
          <div className="flex-1 overflow-hidden p-4">
            {rightView === 'preview' && <LivePreview />}
            {rightView === 'logs' && <LogsView logs={logs} />}
          </div>
        </div>
      </main>
    </div>
  );
}

    